name: Docker Image CI
on:
  push:
    branches: ["main"]
    paths:
      - furdb_core/**
      - furdb/**
      - Dockerfile
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build the Docker Image
        run: docker build . --file Dockerfile --tag madhavanraja/furdb:latest
      - name: Docker Push
        run: docker push madhavanraja/furdb:latest
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
          repository: madhavanraja/furdb
